// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjYWGESrIxNJa1cgEjcWP0N775KAhNKmU',
    appId: '1:170257285644:web:7b054e04229d482ba96429',
    messagingSenderId: '170257285644',
    projectId: 'flutterfire-58ec2',
    authDomain: 'flutterfire-58ec2.firebaseapp.com',
    storageBucket: 'flutterfire-58ec2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFqqx08rsDvm3IwUKt9xVbbprg7s4BizM',
    appId: '1:170257285644:android:392f460244cce94aa96429',
    messagingSenderId: '170257285644',
    projectId: 'flutterfire-58ec2',
    storageBucket: 'flutterfire-58ec2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy4PhzR4G6yVYPTS8aj93hvt07FZ_oXzg',
    appId: '1:170257285644:ios:259b7e77da82b7afa96429',
    messagingSenderId: '170257285644',
    projectId: 'flutterfire-58ec2',
    storageBucket: 'flutterfire-58ec2.appspot.com',
    iosClientId: '170257285644-lhld54kj63adc49jde7676daqfvrbjur.apps.googleusercontent.com',
    iosBundleId: 'com.example.june26',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy4PhzR4G6yVYPTS8aj93hvt07FZ_oXzg',
    appId: '1:170257285644:ios:259b7e77da82b7afa96429',
    messagingSenderId: '170257285644',
    projectId: 'flutterfire-58ec2',
    storageBucket: 'flutterfire-58ec2.appspot.com',
    iosClientId: '170257285644-lhld54kj63adc49jde7676daqfvrbjur.apps.googleusercontent.com',
    iosBundleId: 'com.example.june26',
  );
}
